# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba2543167f9fe73dff97ab95f4ee84cb9a1e15db7da2b194cfb1bd47e4f24e818ee00d7f1c84c86fc3e4449161fa30d74ccdfc8a8a764acb3c6c63415afeb5a0

test:
  secret_key_base: f3facd5af1647e170cfbaf04e221814b39fc1b7a035f3de6928b6ddebfbe385c6f232a8a9ab0c5853a0e45f67b6f66a677b92be555dba2e2cc9c70f267418336

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
